name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emscripten
        run: |
            git clone https://github.com/emscripten-core/emsdk.git
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest
            echo "Setting up environment variables for Emscripten..."
            echo "export PATH=$(pwd)/emsdk:$PATH" >> $GITHUB_ENV
            echo "export PATH=$(pwd)/emsdk/upstream/emscripten:$PATH" >> $GITHUB_ENV
            echo "export EMSDK=$(pwd)/emsdk" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: |
          make local -C ./wasm/src/
          pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
